### ISSUE TITLE
got this error while running the code

### ISSUE THREAD

**Issue by lakshya3612** [ravigithub19/ai-virtual-mouse-controller#3]
Traceback (most recent call last):
  File "C:/Users/hp/Documents/HandTrackingModule.py", line 108, in <module>
    main()
  File "C:/Users/hp/Documents/HandTrackingModule.py", line 95, in main
    img = detector.findHands(img)
  File "C:/Users/hp/Documents/HandTrackingModule.py", line 21, in findHands
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-i3ohmhl0\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

please help me to get rid of this error

**Comment by amankumar2013** [comment]
I am also facing this problem!!!!!

**Comment by SAMIR672160** [comment]
Traceback (most recent call last):
  File "C:/Users/samir/PycharmProjects/AiVirtualMouseProject/AiVirtualMouseProject.py", line 26, in <module>
    img = detector.findHands(img)
  File "C:\Users\samir\PycharmProjects\AiVirtualMouseProject\HandTrackingModule.py", line 21, in findHands
    imgRGB = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

[ WARN:1@17.149] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

Process finished with exit code 1
